#:kivy 2.1.0
<TaskScreen>:
    MDBoxLayout:
        orientation: 'vertical'
        padding:dp(0), dp(70), dp(0), dp(0)
        SearchE4:
            id: search_item
            mode: "rectangle"
            hint_text: "Buscar..."
            icon_right: "magnify"
            size_hint_x: 0.9
            pos_hint: {'center_x': 0.5}
            on_text: root.calc(self.text)
        MDScrollView:
            MDList:
                id: tareas