#:import ZBarCam kivy_garden.zbarcam.ZBarCam
#:import ZBarSymbol pyzbar.pyzbar.ZBarSymbol

<InventoryScreen>:
    id: inventory
    MDBoxLayout:
        orientation:"vertical"
        pos_hint: {'center_y': .39, 'x': .0}
        MDScrollView:
            MDList:
                id: list
    MDRectangleFlatButton:
        pos_hint: {'center_y': 0.80, 'x': 0.8}
        on_release: root.open_camera()
        MDIcon:
            icon: 'camera'
            halign: 'center'
