<ReportScreen>:
    MDBoxLayout:
        orientation: "vertical"
        padding:0, 70, 0, 0
        SearchE4:
            id: search
            hint_text: "Buscar..."
            mode: "round"
            pos_hint: {'center_x': 0.5}
            size_hint_x: 0.9
            on_text: root.buscar_informe(self.text) 
        MDScrollView:
            MDList:
                id: informes
        
        