<DeteilsQuestionaryScreen>:
MDScreen:
    name: "Estat"
    MDBoxLayout:
        padding:0, 50, 0, 0
        orientation: "vertical"
    MDLabel:
        id: estatext
        text:"Splash Screen"
        halign: "center"
        font_style: "H5"
    Image:
        id: imagen
        source: 'Images/load.gif'
        center: self.parent.center
        size: 600, 600
    MDScrollView:
        MDList:
            id: estat