#:kivy 2.1.0
<BudgetScreen>:
    MDBoxLayout:
        orientation: 'vertical'
        padding:dp(0), dp(70), dp(0), dp(0)
        SearchE4:
            id: search_item
            hint_text: "Buscar..."
            mode: "rectangle"
            icon_right: "magnify"
            pos_hint: {'center_x': 0.5}
            size_hint_x: 0.9
            on_text: root.calc(self.text) 
        MDScrollView:
            MDList:
                id: presupuesto